# https://github.com/marketplace/actions/unity-activate
name: Activate Unity License
on: [ workflow_dispatch ]

jobs:
  activate:
    name: Activate Unity License
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.1f1