name: Build

on:
  workflow_call:
    inputs:
      targetPlatform:
        required: true
        type: string
      unityVersion:
        required: true
        type: string
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true


jobs:
  build:
    name: Build for ${{ inputs.targetPlatform }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      
      # Cache Library/ folder, should speed up build times by about 50%
      - name: Retrieve cached library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ inputs.targetPlatform }}
          restore-keys: |
            Library-
      
      # Build the actual game
      - name: Build the actual game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: ${{ github.event.repository.name }}
          versioning: None
          # To fix the Warning: Could not parse "none" to semver, defaulting android version code to 1 warning
          androidVersionCode: 1
          unityVersion: ${{ inputs.unityVersion }}
          targetPlatform: ${{ inputs.targetPlatform }}
      
      # Upload the generated build
      - name: Upload generated build
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ inputs.targetPlatform }}
          path: build/${{ inputs.targetPlatform }}