name: CI

on: [ push ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  buildAndTestForSomePlatforms:
    needs: [ lint ]
    uses: ./.github/workflows/build.yml
  
  release:
    needs:
      - lint
      - buildAndTestForSomePlatforms
    uses: ./.github/workflows/release.yml