name: CI
on: [ push ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  
  buildForWindows64:
    name: Build for Windows x64
    if:
      contains('
      refs/heads/main
      refs/heads/alpha
      ', github.ref)
    needs:
      - lint
      - test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      # Available target platforms. Dedicated servers require a special flag, look into it when needed
      # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
      # - StandaloneWindows # Build a Windows 32-bit standalone.
      # - StandaloneWindows64 # Build a Windows 64-bit standalone.
      # - StandaloneLinux64 # Build a Linux 64-bit standalone.
      # - iOS # Build an iOS player.
      # - Android # Build an Android player.
      # - WebGL # WebGL.
      targetPlatform: StandaloneWindows64
      unityVersion: 2021.3.1f1
  
  release:
    needs: [ buildForWindows64 ]
    uses: ./.github/workflows/release.yml