# Adapted from https://github.com/adrenak/upm-template/blob/master/.github/workflows/ci.yml
# https://github.com/marketplace/actions/action-for-semantic-release
name: Release
on: [ workflow_call ]  # allow this workflow to be called from other workflows
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Windows x64 build
        uses: actions/download-artifact@v2
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}